In [1]:
import os
from dotenv import load_dotenv

In [23]:
load_dotenv()

API_KEY = os.getenv("CPCB_API_KEY")

if API_KEY:
    print("API key loaded successfully!")
else:
    print("API key not found!")

API key loaded successfully!

In [2]:
import requests

In [25]:
url = "https://api.data.gov.in/resource/3b01bcb8-0b14-4abf-b6f2-c1bfd384ba69"

params = {
    "api-key": API_KEY,
    "format": "json",
    "limit": 1
}

response = requests.get(url, params=params, timeout=120)

print("Status Code:", response.status_code)

Status Code: 502

In [26]:
load_dotenv()

API_KEY = os.getenv("CPCB_API_KEY")

url = (
    "https://api.data.gov.in/resource/"
    "3b01bcb8-0b14-4abf-b6f2-c1bfd384ba69"
    f"?api-key={API_KEY}"
    "&format=json"
    "&offset=0"
    "&limit=1"
)

print("Sending request...")

response = requests.get(
    url,
    headers={
        "User-Agent": "Mozilla/5.0"
    },
    timeout=120
)

print("Status Code:", response.status_code)
print("Response:", response.text[:1000])

Sending request...
Status Code: 200
Response: {
    "index_name": "3b01bcb8-0b14-4abf-b6f2-c1bfd384ba69",
    "title": "Real time Air Quality Index from various locations",
    "desc": "Real time Air Quality Index from various locations",
    "org_type": "Central",
    "org": [
        "Ministry of Environment, Forest and Climate Change",
        "Central Pollution Control Board"
    ],
    "sector": [
        "Environment and Forest",
        "Industrial Air Pollution",
        "Residential Air Pollution",
        "Vehicular Air Pollution"
    ],
    "source": "data.gov.in",
    "catalog_uuid": "a3e7afc6-b799-4ede-b143-8e074b27e062",
    "visualizable": "1",
    "active": "1",
    "created": 1470249000,
    "updated": 1786266118,
    "created_date": "2016-04-08T00:00:00Z",
    "updated_date": "2026-08-09T09:01:58Z",
    "external_ws": 0,
    "external_ws_url": "",
    "target_bucket": {
        "index": "air_quality",
        "type": "3b01bcb8-0b14-4abf-b6f2-c1bfd384ba69"
    },
    "field": [
        {
            "name": "count

In [27]:
data = response.json()

print("Total records available:", data.get("total"))
print("Records received:", len(data.get("records", [])))

Total records available: 3402
Records received: 1

In [28]:
records = data.get("records", [])

print(records[0])

{'country': 'India', 'state': 'Bihar', 'city': 'Patna', 'station': 'Samanpura, Patna - BSPCB', 'last_update': '09-08-2026 14:00:00', 'latitude': '25.596727', 'longitude': '85.085624', 'pollutant_id': 'NO2', 'min_value': '24', 'max_value': '25', 'avg_value': '24'}

In [29]:
api_url = (
    "https://api.data.gov.in/resource/"
    "3b01bcb8-0b14-4abf-b6f2-c1bfd384ba69"
    f"?api-key={API_KEY}"
    "&format=json"
    "&offset=0"
    "&limit=10"
)

print("Requesting 10 records...")

response = requests.get(
    api_url,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=180
)

print("Status Code:", response.status_code)

if response.status_code == 200:
    data = response.json()
    print("Total available:", data.get("total"))
    print("Records received:", len(data.get("records", [])))
else:
    print("Request failed.")
    print(response.text[:500])

Requesting 10 records...
Status Code: 200
Total available: 3402
Records received: 10

In [3]:
import requests
import pandas as pd
import time

In [31]:
all_records = []

limit = 10
offset = 0
total = 3402

while offset < total:

    api_url = (
        "https://api.data.gov.in/resource/"
        "3b01bcb8-0b14-4abf-b6f2-c1bfd384ba69"
        f"?api-key={API_KEY}"
        "&format=json"
        f"&offset={offset}"
        f"&limit={limit}"
    )

    try:
        response = requests.get(
            api_url,
            headers={"User-Agent": "Mozilla/5.0"},
            timeout=180
        )

        if response.status_code == 200:

            data = response.json()
            records = data.get("records", [])

            all_records.extend(records)

            print(
                f"Fetched {len(records)} | "
                f"Total collected: {len(all_records)} / {total}"
            )

            if len(records) == 0:
                print("No more records available.")
                break

            offset += len(records)

            time.sleep(1)

        else:
            print("Error:", response.status_code)
            break

    except requests.exceptions.Timeout:
        print(f"Timeout at offset {offset}. Retrying...")
        time.sleep(5)
        continue

print("Finished!")
print("Total records collected:", len(all_records))

Fetched 10 | Total collected: 10 / 3402
Fetched 10 | Total collected: 20 / 3402
Fetched 10 | Total collected: 30 / 3402
Fetched 10 | Total collected: 40 / 3402
Fetched 10 | Total collected: 50 / 3402
Fetched 10 | Total collected: 60 / 3402
Fetched 10 | Total collected: 70 / 3402
Fetched 10 | Total collected: 80 / 3402
Fetched 10 | Total collected: 90 / 3402
Fetched 10 | Total collected: 100 / 3402
Fetched 10 | Total collected: 110 / 3402
Fetched 10 | Total collected: 120 / 3402
Fetched 10 | Total collected: 130 / 3402
Fetched 10 | Total collected: 140 / 3402
Fetched 10 | Total collected: 150 / 3402
Fetched 10 | Total collected: 160 / 3402
Fetched 10 | Total collected: 170 / 3402
Fetched 10 | Total collected: 180 / 3402
Fetched 10 | Total collected: 190 / 3402
Fetched 10 | Total collected: 200 / 3402
Fetched 10 | Total collected: 210 / 3402
Fetched 10 | Total collected: 220 / 3402
Fetched 10 | Total collected: 230 / 3402
Fetched 10 | Total collected: 240 / 3402
Fetched 10 | Total collected: 250 / 3402
Fetched 10 | Total collected: 260 / 3402
Fetched 10 | Total collected: 270 / 3402
Fetched 10 | Total collected: 280 / 3402
Fetched 10 | Total collected: 290 / 3402
Fetched 10 | Total collected: 300 / 3402
Fetched 10 | Total collected: 310 / 3402
Fetched 10 | Total collected: 320 / 3402
Fetched 10 | Total collected: 330 / 3402
Fetched 10 | Total collected: 340 / 3402
Fetched 10 | Total collected: 350 / 3402
Fetched 10 | Total collected: 360 / 3402
Fetched 10 | Total collected: 370 / 3402
Fetched 10 | Total collected: 380 / 3402
Fetched 10 | Total collected: 390 / 3402
Fetched 10 | Total collected: 400 / 3402
Fetched 10 | Total collected: 410 / 3402
Fetched 10 | Total collected: 420 / 3402
Fetched 10 | Total collected: 430 / 3402
Fetched 10 | Total collected: 440 / 3402
Fetched 10 | Total collected: 450 / 3402
Fetched 10 | Total collected: 460 / 3402
Fetched 10 | Total collected: 470 / 3402
Fetched 10 | Total collected: 480 / 3402
Fetched 10 | Total collected: 490 / 3402
Fetched 10 | Total collected: 500 / 3402
Fetched 10 | Total collected: 510 / 3402
Fetched 10 | Total collected: 520 / 3402
Fetched 10 | Total collected: 530 / 3402
Fetched 10 | Total collected: 540 / 3402
Fetched 10 | Total collected: 550 / 3402
Fetched 10 | Total collected: 560 / 3402
Fetched 10 | Total collected: 570 / 3402
Fetched 10 | Total collected: 580 / 3402
Fetched 10 | Total collected: 590 / 3402
Fetched 10 | Total collected: 600 / 3402
Fetched 10 | Total collected: 610 / 3402
Fetched 10 | Total collected: 620 / 3402
Fetched 10 | Total collected: 630 / 3402
Fetched 10 | Total collected: 640 / 3402
Fetched 10 | Total collected: 650 / 3402
Fetched 10 | Total collected: 660 / 3402
Fetched 10 | Total collected: 670 / 3402
Fetched 10 | Total collected: 680 / 3402
Fetched 10 | Total collected: 690 / 3402
Fetched 10 | Total collected: 700 / 3402
Fetched 10 | Total collected: 710 / 3402
Fetched 10 | Total collected: 720 / 3402
Fetched 10 | Total collected: 730 / 3402
Fetched 10 | Total collected: 740 / 3402
Fetched 10 | Total collected: 750 / 3402
Fetched 10 | Total collected: 760 / 3402
Fetched 10 | Total collected: 770 / 3402
Fetched 10 | Total collected: 780 / 3402
Fetched 10 | Total collected: 790 / 3402
Fetched 10 | Total collected: 800 / 3402
Fetched 10 | Total collected: 810 / 3402
Fetched 10 | Total collected: 820 / 3402
Fetched 10 | Total collected: 830 / 3402
Fetched 10 | Total collected: 840 / 3402
Fetched 10 | Total collected: 850 / 3402
Fetched 10 | Total collected: 860 / 3402
Fetched 10 | Total collected: 870 / 3402
Fetched 10 | Total collected: 880 / 3402
Fetched 10 | Total collected: 890 / 3402
Fetched 10 | Total collected: 900 / 3402
Fetched 10 | Total collected: 910 / 3402
Timeout at offset 910. Retrying...
Fetched 10 | Total collected: 920 / 3402
Fetched 10 | Total collected: 930 / 3402
Fetched 10 | Total collected: 940 / 3402
Fetched 10 | Total collected: 950 / 3402
Fetched 10 | Total collected: 960 / 3402
Fetched 10 | Total collected: 970 / 3402
Fetched 10 | Total collected: 980 / 3402
Fetched 10 | Total collected: 990 / 3402
Fetched 10 | Total collected: 1000 / 3402
Fetched 10 | Total collected: 1010 / 3402
Fetched 10 | Total collected: 1020 / 3402
Fetched 10 | Total collected: 1030 / 3402
Fetched 10 | Total collected: 1040 / 3402
Fetched 10 | Total collected: 1050 / 3402
Fetched 10 | Total collected: 1060 / 3402
Fetched 10 | Total collected: 1070 / 3402
Fetched 10 | Total collected: 1080 / 3402
Fetched 10 | Total collected: 1090 / 3402
Fetched 10 | Total collected: 1100 / 3402
Fetched 10 | Total collected: 1110 / 3402
Fetched 10 | Total collected: 1120 / 3402
Fetched 10 | Total collected: 1130 / 3402
Fetched 10 | Total collected: 1140 / 3402
Fetched 10 | Total collected: 1150 / 3402
Fetched 10 | Total collected: 1160 / 3402
Fetched 10 | Total collected: 1170 / 3402
Fetched 10 | Total collected: 1180 / 3402
Fetched 10 | Total collected: 1190 / 3402
Fetched 10 | Total collected: 1200 / 3402
Fetched 10 | Total collected: 1210 / 3402
Fetched 10 | Total collected: 1220 / 3402
Fetched 10 | Total collected: 1230 / 3402
Fetched 10 | Total collected: 1240 / 3402
Fetched 10 | Total collected: 1250 / 3402
Fetched 10 | Total collected: 1260 / 3402
Fetched 10 | Total collected: 1270 / 3402
Fetched 10 | Total collected: 1280 / 3402
Fetched 10 | Total collected: 1290 / 3402
Timeout at offset 1290. Retrying...
Fetched 10 | Total collected: 1300 / 3402
Fetched 10 | Total collected: 1310 / 3402
Fetched 10 | Total collected: 1320 / 3402
Fetched 10 | Total collected: 1330 / 3402
Fetched 10 | Total collected: 1340 / 3402
Fetched 10 | Total collected: 1350 / 3402
Fetched 10 | Total collected: 1360 / 3402
Fetched 10 | Total collected: 1370 / 3402
Fetched 10 | Total collected: 1380 / 3402
Fetched 10 | Total collected: 1390 / 3402
Fetched 10 | Total collected: 1400 / 3402
Fetched 10 | Total collected: 1410 / 3402
Fetched 10 | Total collected: 1420 / 3402
Fetched 10 | Total collected: 1430 / 3402
Fetched 10 | Total collected: 1440 / 3402
Fetched 10 | Total collected: 1450 / 3402
Fetched 10 | Total collected: 1460 / 3402
Fetched 10 | Total collected: 1470 / 3402
Fetched 10 | Total collected: 1480 / 3402
Fetched 10 | Total collected: 1490 / 3402
Fetched 10 | Total collected: 1500 / 3402
Fetched 10 | Total collected: 1510 / 3402
Fetched 10 | Total collected: 1520 / 3402
Fetched 10 | Total collected: 1530 / 3402
Fetched 10 | Total collected: 1540 / 3402
Fetched 10 | Total collected: 1550 / 3402
Fetched 10 | Total collected: 1560 / 3402
Fetched 10 | Total collected: 1570 / 3402
Fetched 10 | Total collected: 1580 / 3402
Fetched 10 | Total collected: 1590 / 3402
Fetched 10 | Total collected: 1600 / 3402
Fetched 10 | Total collected: 1610 / 3402
Fetched 10 | Total collected: 1620 / 3402
Fetched 10 | Total collected: 1630 / 3402
Fetched 10 | Total collected: 1640 / 3402
Fetched 10 | Total collected: 1650 / 3402
Fetched 10 | Total collected: 1660 / 3402
Fetched 10 | Total collected: 1670 / 3402
Fetched 10 | Total collected: 1680 / 3402
Fetched 10 | Total collected: 1690 / 3402
Fetched 10 | Total collected: 1700 / 3402
Fetched 10 | Total collected: 1710 / 3402
Fetched 10 | Total collected: 1720 / 3402
Timeout at offset 1720. Retrying...
Fetched 10 | Total collected: 1730 / 3402
Fetched 10 | Total collected: 1740 / 3402
Fetched 10 | Total collected: 1750 / 3402
Fetched 10 | Total collected: 1760 / 3402
Fetched 10 | Total collected: 1770 / 3402
Fetched 10 | Total collected: 1780 / 3402
Fetched 10 | Total collected: 1790 / 3402
Fetched 10 | Total collected: 1800 / 3402
Fetched 10 | Total collected: 1810 / 3402
Fetched 10 | Total collected: 1820 / 3402
Fetched 10 | Total collected: 1830 / 3402
Fetched 10 | Total collected: 1840 / 3402
Fetched 10 | Total collected: 1850 / 3402
Fetched 10 | Total collected: 1860 / 3402
Timeout at offset 1860. Retrying...
Fetched 10 | Total collected: 1870 / 3402
Fetched 10 | Total collected: 1880 / 3402
Fetched 10 | Total collected: 1890 / 3402
Fetched 10 | Total collected: 1900 / 3402
Fetched 10 | Total collected: 1910 / 3402
Fetched 10 | Total collected: 1920 / 3402
Fetched 10 | Total collected: 1930 / 3402
Fetched 10 | Total collected: 1940 / 3402
Fetched 10 | Total collected: 1950 / 3402
Fetched 10 | Total collected: 1960 / 3402
Fetched 10 | Total collected: 1970 / 3402
Fetched 10 | Total collected: 1980 / 3402
Fetched 10 | Total collected: 1990 / 3402
Fetched 10 | Total collected: 2000 / 3402
Fetched 10 | Total collected: 2010 / 3402
Fetched 10 | Total collected: 2020 / 3402
Fetched 10 | Total collected: 2030 / 3402
Fetched 10 | Total collected: 2040 / 3402
Fetched 10 | Total collected: 2050 / 3402
Fetched 10 | Total collected: 2060 / 3402
Fetched 10 | Total collected: 2070 / 3402
Fetched 10 | Total collected: 2080 / 3402
Fetched 10 | Total collected: 2090 / 3402
Fetched 10 | Total collected: 2100 / 3402
Fetched 10 | Total collected: 2110 / 3402
Fetched 10 | Total collected: 2120 / 3402
Fetched 10 | Total collected: 2130 / 3402
Fetched 10 | Total collected: 2140 / 3402
Fetched 10 | Total collected: 2150 / 3402
Fetched 10 | Total collected: 2160 / 3402
Fetched 10 | Total collected: 2170 / 3402
Fetched 10 | Total collected: 2180 / 3402
Fetched 10 | Total collected: 2190 / 3402
Fetched 10 | Total collected: 2200 / 3402
Fetched 10 | Total collected: 2210 / 3402
Fetched 10 | Total collected: 2220 / 3402
Fetched 10 | Total collected: 2230 / 3402
Timeout at offset 2230. Retrying...
Fetched 10 | Total collected: 2240 / 3402
Fetched 10 | Total collected: 2250 / 3402
Fetched 10 | Total collected: 2260 / 3402
Fetched 10 | Total collected: 2270 / 3402
Fetched 10 | Total collected: 2280 / 3402
Fetched 10 | Total collected: 2290 / 3402
Fetched 10 | Total collected: 2300 / 3402
Fetched 10 | Total collected: 2310 / 3402
Fetched 10 | Total collected: 2320 / 3402
Fetched 10 | Total collected: 2330 / 3402
Fetched 10 | Total collected: 2340 / 3402
Fetched 10 | Total collected: 2350 / 3402
Fetched 10 | Total collected: 2360 / 3402
Fetched 10 | Total collected: 2370 / 3402
Fetched 10 | Total collected: 2380 / 3402
Fetched 10 | Total collected: 2390 / 3402
Fetched 10 | Total collected: 2400 / 3402
Fetched 10 | Total collected: 2410 / 3402
Fetched 10 | Total collected: 2420 / 3402
Fetched 10 | Total collected: 2430 / 3402
Fetched 10 | Total collected: 2440 / 3402
Fetched 10 | Total collected: 2450 / 3402
Fetched 10 | Total collected: 2460 / 3402
Fetched 10 | Total collected: 2470 / 3402
Fetched 10 | Total collected: 2480 / 3402
Fetched 10 | Total collected: 2490 / 3402
Fetched 10 | Total collected: 2500 / 3402
Fetched 10 | Total collected: 2510 / 3402
Fetched 10 | Total collected: 2520 / 3402
Fetched 10 | Total collected: 2530 / 3402
Fetched 10 | Total collected: 2540 / 3402
Fetched 10 | Total collected: 2550 / 3402
Fetched 10 | Total collected: 2560 / 3402
Fetched 10 | Total collected: 2570 / 3402
Fetched 10 | Total collected: 2580 / 3402
Fetched 10 | Total collected: 2590 / 3402
Fetched 10 | Total collected: 2600 / 3402
Fetched 10 | Total collected: 2610 / 3402
Fetched 10 | Total collected: 2620 / 3402
Fetched 10 | Total collected: 2630 / 3402
Fetched 10 | Total collected: 2640 / 3402
Fetched 10 | Total collected: 2650 / 3402
Fetched 10 | Total collected: 2660 / 3402
Fetched 10 | Total collected: 2670 / 3402
Fetched 10 | Total collected: 2680 / 3402
Fetched 10 | Total collected: 2690 / 3402
Fetched 10 | Total collected: 2700 / 3402
Fetched 10 | Total collected: 2710 / 3402
Fetched 10 | Total collected: 2720 / 3402
Fetched 10 | Total collected: 2730 / 3402
Fetched 10 | Total collected: 2740 / 3402
Fetched 10 | Total collected: 2750 / 3402
Fetched 10 | Total collected: 2760 / 3402
Fetched 10 | Total collected: 2770 / 3402
Fetched 10 | Total collected: 2780 / 3402
Fetched 10 | Total collected: 2790 / 3402
Fetched 10 | Total collected: 2800 / 3402
Fetched 10 | Total collected: 2810 / 3402
Fetched 10 | Total collected: 2820 / 3402
Fetched 10 | Total collected: 2830 / 3402
Fetched 10 | Total collected: 2840 / 3402
Fetched 10 | Total collected: 2850 / 3402
Fetched 10 | Total collected: 2860 / 3402
Fetched 10 | Total collected: 2870 / 3402
Fetched 10 | Total collected: 2880 / 3402
Fetched 10 | Total collected: 2890 / 3402
Fetched 10 | Total collected: 2900 / 3402
Fetched 10 | Total collected: 2910 / 3402
Fetched 10 | Total collected: 2920 / 3402
Fetched 10 | Total collected: 2930 / 3402
Fetched 10 | Total collected: 2940 / 3402
Fetched 10 | Total collected: 2950 / 3402
Fetched 10 | Total collected: 2960 / 3402
Fetched 10 | Total collected: 2970 / 3402
Fetched 10 | Total collected: 2980 / 3402
Fetched 10 | Total collected: 2990 / 3402
Fetched 10 | Total collected: 3000 / 3402
Fetched 10 | Total collected: 3010 / 3402
Fetched 10 | Total collected: 3020 / 3402
Fetched 10 | Total collected: 3030 / 3402
Fetched 10 | Total collected: 3040 / 3402
Fetched 10 | Total collected: 3050 / 3402
Fetched 10 | Total collected: 3060 / 3402
Fetched 10 | Total collected: 3070 / 3402
Fetched 10 | Total collected: 3080 / 3402
Fetched 10 | Total collected: 3090 / 3402
Fetched 10 | Total collected: 3100 / 3402
Fetched 10 | Total collected: 3110 / 3402
Fetched 10 | Total collected: 3120 / 3402
Fetched 10 | Total collected: 3130 / 3402
Fetched 10 | Total collected: 3140 / 3402
Fetched 10 | Total collected: 3150 / 3402
Timeout at offset 3150. Retrying...
Fetched 10 | Total collected: 3160 / 3402
Fetched 10 | Total collected: 3170 / 3402
Fetched 10 | Total collected: 3180 / 3402
Fetched 10 | Total collected: 3190 / 3402
Fetched 10 | Total collected: 3200 / 3402
Fetched 10 | Total collected: 3210 / 3402
Fetched 10 | Total collected: 3220 / 3402
Fetched 10 | Total collected: 3230 / 3402
Fetched 10 | Total collected: 3240 / 3402
Fetched 10 | Total collected: 3250 / 3402
Fetched 10 | Total collected: 3260 / 3402
Fetched 10 | Total collected: 3270 / 3402
Fetched 10 | Total collected: 3280 / 3402
Fetched 10 | Total collected: 3290 / 3402
Fetched 10 | Total collected: 3300 / 3402
Fetched 10 | Total collected: 3310 / 3402
Fetched 10 | Total collected: 3320 / 3402
Fetched 10 | Total collected: 3330 / 3402
Fetched 10 | Total collected: 3340 / 3402
Fetched 10 | Total collected: 3350 / 3402
Fetched 10 | Total collected: 3360 / 3402
Fetched 10 | Total collected: 3370 / 3402
Fetched 10 | Total collected: 3380 / 3402
Fetched 10 | Total collected: 3390 / 3402
Fetched 10 | Total collected: 3400 / 3402
Fetched 2 | Total collected: 3402 / 3402
Finished!
Total records collected: 3402

In [32]:
print("Records currently collected:", len(all_records))

Records currently collected: 3402

In [33]:
df = pd.DataFrame(all_records)

print("Shape:", df.shape)

Shape: (3402, 11)

In [34]:
print(df.columns.tolist())

['country', 'state', 'city', 'station', 'last_update', 'latitude', 'longitude', 'pollutant_id', 'min_value', 'max_value', 'avg_value']

In [35]:
df.head()

,country,state,city,station,last_update,latitude,longitude,pollutant_id,min_value,max_value,avg_value
0,India,Chhattisgarh,Tumidih,"OP Jindal Industrial Park, Tumidih - CECB",09-08-2026 14:00:00,22.06631475,83.33820077,NH3,1,2,2
1,India,Chhattisgarh,Tumidih,"OP Jindal Industrial Park, Tumidih - CECB",09-08-2026 14:00:00,22.06631475,83.33820077,OZONE,14,23,18
2,India,Delhi,Delhi,"ITO, Delhi - CPCB",09-08-2026 14:00:00,28.628624,77.24106,PM10,23,133,80
3,India,Delhi,Delhi,"ITO, Delhi - CPCB",09-08-2026 14:00:00,28.628624,77.24106,NH3,3,6,5
4,India,Delhi,Delhi,"ITO, Delhi - CPCB",09-08-2026 14:00:00,28.628624,77.24106,OZONE,27,35,31

In [36]:
df.to_csv("../data/cpcb_raw.csv", index=False)

print("CPCB raw data saved successfully!")

CPCB raw data saved successfully!

In [4]:
df = pd.read_csv("../data/cpcb_raw.csv")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 3402
Columns: 11

In [5]:
print(df.columns.tolist())

['country', 'state', 'city', 'station', 'last_update', 'latitude', 'longitude', 'pollutant_id', 'min_value', 'max_value', 'avg_value']

In [7]:
df.head()

,country,state,city,station,last_update,latitude,longitude,pollutant_id,min_value,max_value,avg_value
0,India,Chhattisgarh,Tumidih,"OP Jindal Industrial Park, Tumidih - CECB",09-08-2026 14:00:00,22.066315,83.338201,NH3,1.0,2.0,2.0
1,India,Chhattisgarh,Tumidih,"OP Jindal Industrial Park, Tumidih - CECB",09-08-2026 14:00:00,22.066315,83.338201,OZONE,14.0,23.0,18.0
2,India,Delhi,Delhi,"ITO, Delhi - CPCB",09-08-2026 14:00:00,28.628624,77.241060,PM10,23.0,133.0,80.0
3,India,Delhi,Delhi,"ITO, Delhi - CPCB",09-08-2026 14:00:00,28.628624,77.241060,NH3,3.0,6.0,5.0
4,India,Delhi,Delhi,"ITO, Delhi - CPCB",09-08-2026 14:00:00,28.628624,77.241060,OZONE,27.0,35.0,31.0

In [8]:
df.tail()

,country,state,city,station,last_update,latitude,longitude,pollutant_id,min_value,max_value,avg_value
3397,India,West Bengal,Kolkata,"Rabindra Sarobar, Kolkata - WBPCB",09-08-2026 14:00:00,22.511060,88.351420,CO,17.0,22.0,19.0
3398,India,West Bengal,Kolkata,"Rabindra Sarobar, Kolkata - WBPCB",09-08-2026 14:00:00,22.511060,88.351420,OZONE,10.0,13.0,12.0
3399,India,West Bengal,Kolkata,"Jadavpur, Kolkata - WBPCB",09-08-2026 14:00:00,22.499290,88.369170,CO,23.0,25.0,24.0
3400,India,West Bengal,Kolkata,"Rabindra Bharati University, Kolkata - WBPCB",09-08-2026 14:00:00,22.627847,88.380669,SO2,8.0,10.0,9.0
3401,India,West Bengal,Kolkata,"Rabindra Bharati University, Kolkata - WBPCB",09-08-2026 14:00:00,22.627847,88.380669,OZONE,55.0,311.0,130.0

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3402 entries, 0 to 3401
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country       3402 non-null   str
 1   state         3402 non-null   str
 2   city          3402 non-null   str
 3   station       3402 non-null   str
 4   last_update   3402 non-null   str
 5   latitude      3402 non-null   float64
 6   longitude     3402 non-null   float64
 7   pollutant_id  3402 non-null   str
 8   min_value     3065 non-null   float64
 9   max_value     3065 non-null   float64
 10  avg_value     3065 non-null   float64
dtypes: float64(5), str(6)
memory usage: 541.8 KB

In [10]:
df.isnull().sum()

country           0
state             0
city              0
station           0
last_update       0
latitude          0
longitude         0
pollutant_id      0
min_value       337
max_value       337
avg_value       337
dtype: int64

In [11]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 754

In [13]:
print(df["pollutant_id"].unique())

<ArrowStringArray>
['NH3', 'OZONE', 'PM10', 'CO', 'PM2.5', 'SO2', 'NO2']
Length: 7, dtype: str